/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BicicletePackage;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabi
 */
public class Interogari extends javax.swing.JFrame {

    /**
     * Creates new form Interogari
     */
    public Interogari() {
        initComponents();
        this.setLocationRelativeTo(null);       //centrul ecranului
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butonq7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        butonq1 = new javax.swing.JButton();
        butonq2 = new javax.swing.JButton();
        butonq3 = new javax.swing.JButton();
        butonq4 = new javax.swing.JButton();
        sediuNume = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sediuNume1 = new javax.swing.JComboBox<>();
        modalitatePlata = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        butonq5 = new javax.swing.JButton();
        butonq6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        butonq8 = new javax.swing.JButton();
        butonq9 = new javax.swing.JButton();
        butonq10 = new javax.swing.JButton();
        inputData = new javax.swing.JTextField();
        nrSponsori = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_home2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 171, 227));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("8.Selectati bicicletele care nu au fost deloc inchiriate dupa");

        butonq7.setBackground(new java.awt.Color(52, 152, 219));
        butonq7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq7.setText("query7");
        butonq7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq7ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1.Afisati detaliile (mai putin id-urile) despre bicicletele ce se gasesc la sediul");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2.Afisati numele si prenumele clientilor care au inchiriat biciclete in total mai mult de");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3.Afisati numele si prenumele pentru angajatii care s-au angajat mai devreme decat");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("managerul(al caruia ii afisati nume + prenume) din sediul lor + numele sediului.");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4.Afisati numele si prenumele clientilor care au inchiriat biciclete folosind");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5.Sa se afiseze detalii despre sponsorii sediului care il au ca manager pe Valentin Mihai.");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6.Afisati Numele si prenumele clientilor care au inchiriat biciclete cu pretul pe ora intre");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ore");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("9.Calculati luna in care s-au inchiriat cele mai multe biciclete, afisati luna si numarul de inchirieri.");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("10.Afisati numele managerilor al caror sedii au cel putin (>=)");

        butonq1.setBackground(new java.awt.Color(52, 152, 219));
        butonq1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq1.setText("query1");
        butonq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq1ActionPerformed(evt);
            }
        });

        butonq2.setBackground(new java.awt.Color(52, 152, 219));
        butonq2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq2.setText("query2");
        butonq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq2ActionPerformed(evt);
            }
        });

        butonq3.setBackground(new java.awt.Color(52, 152, 219));
        butonq3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq3.setText("query3");
        butonq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq3ActionPerformed(evt);
            }
        });

        butonq4.setBackground(new java.awt.Color(52, 152, 219));
        butonq4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq4.setText("query4");
        butonq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq4ActionPerformed(evt);
            }
        });

        sediuNume.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BNBikes", "Relax", "MyBike", "Adventure" }));
        sediuNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sediuNumeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("7.Gasiti angajatii cu cel mai mic salariu din fiecare sediu, apoi sortati crescator dupa salariu.");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Interogari simple");

        sediuNume1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BNBikes", "Relax", "MyBike", "Adventure" }));
        sediuNume1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sediuNume1ActionPerformed(evt);
            }
        });

        modalitatePlata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "card" }));
        modalitatePlata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalitatePlataActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("la sediul");

        butonq5.setBackground(new java.awt.Color(52, 152, 219));
        butonq5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq5.setText("query5");
        butonq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq5ActionPerformed(evt);
            }
        });

        butonq6.setBackground(new java.awt.Color(52, 152, 219));
        butonq6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq6.setText("query6");
        butonq6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq6ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Interogari complexe");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("si");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("de lei.");

        butonq8.setBackground(new java.awt.Color(52, 152, 219));
        butonq8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq8.setText("query8");
        butonq8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq8ActionPerformed(evt);
            }
        });

        butonq9.setBackground(new java.awt.Color(52, 152, 219));
        butonq9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq9.setText("query9");
        butonq9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq9ActionPerformed(evt);
            }
        });

        butonq10.setBackground(new java.awt.Color(52, 152, 219));
        butonq10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        butonq10.setText("query10");
        butonq10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonq10ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("sponsori.");

        btn_home2.setBackground(new java.awt.Color(1, 50, 67));
        btn_home2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        btn_home2.setForeground(new java.awt.Color(255, 255, 255));
        btn_home2.setText("HOME");
        btn_home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butonq9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butonq8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butonq7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modalitatePlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sediuNume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(sediuNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_home2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(butonq1)
                                        .addComponent(butonq2)
                                        .addComponent(butonq3)
                                        .addComponent(butonq4)
                                        .addComponent(butonq5)
                                        .addComponent(butonq6)))))
                        .addGap(152, 152, 152))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nrSponsori, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonq10)
                        .addGap(144, 144, 144))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sediuNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butonq2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modalitatePlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sediuNume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonq4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonq5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonq6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butonq1)
                        .addGap(102, 102, 102)
                        .addComponent(butonq3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonq7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonq8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonq9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nrSponsori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butonq10)))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sediuNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sediuNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sediuNumeActionPerformed

    private void butonq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq4ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT DISTINCT C.Nume, C.Prenume FROM Clienti C \n" +
                    "INNER JOIN ClientiBiciclete CB ON C.ClientID = CB.ClientID\n" +
                    "INNER JOIN Biciclete B ON CB.BicicletaID = B.BicicletaID\n" +
                    "INNER JOIN Sedii S ON B.SediuID = S.SediuID\n" +
                    "WHERE S.Nume = ? AND CB.ModalitatePlata=?\n" +
                    "GROUP BY C.Nume, C.Prenume";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,sediuNume1.getSelectedItem().toString());
            ps.setString(2,modalitatePlata.getSelectedItem().toString());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq4ActionPerformed

    private void butonq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq3ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT A.Nume + ' ' + A.Prenume AS Angajat, S.Nume AS NumeSediu, \n" +
        "AN.Nume + ' ' +AN.Prenume AS Manager FROM Angajati A\n" +
        "INNER JOIN Sedii S ON A.SediuID = S.SediuID\n" +
        "INNER JOIN Angajati AN ON AN.AngajatID = S.ManagerID\n" +
        "WHERE A.DataAngajarii < AN.DataAngajarii";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq3ActionPerformed

    private void butonq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq2ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT C.Nume, C.Prenume, SUM(DurataInchiriereInOre) AS TotalOre\n" +
        "FROM Clienti C INNER JOIN ClientiBiciclete CB ON C.ClientID = CB.ClientID\n" +
        "GROUP BY C.ClientID, C.Nume, C.Prenume\n" +
        "HAVING SUM(DurataInchiriereInOre) > ?\n" +
        "ORDER BY SUM(DurataInchiriereInOre) ASC";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,jTextField1.getText());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq2ActionPerformed

    private void butonq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT S.Nume AS NumeSediu, B.Producator, B.Serie, B.Culoare, B.MaterialCadru, B.NumarViteze, B.PretInchirierePeOra\n" +
        "FROM Biciclete B INNER JOIN Sedii S\n" +
        "ON B.SediuID = S.SediuID\n" +
        "WHERE S.Nume = ?";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,sediuNume.getSelectedItem().toString());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq1ActionPerformed

    private void butonq7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq7ActionPerformed
        // TODO add your handling code here:

        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT a1.Nume, a1.Prenume, a1.Salariu, s1.Nume as NumeSediu\n" +
                    "FROM Angajati a1 INNER JOIN Sedii s1 ON a1.SediuID = s1.SediuID\n" +
                    "WHERE a1.Salariu IN\n" +
                    "(SELECT MIN(a2.Salariu) FROM Angajati a2\n" +
                    "WHERE a2.SediuID=a1.SediuID\n" +
                    "GROUP BY SediuID)\n" +
                    "ORDER BY Salariu ASC";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq7ActionPerformed

    private void sediuNume1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sediuNume1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sediuNume1ActionPerformed

    private void modalitatePlataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalitatePlataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalitatePlataActionPerformed

    private void butonq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq5ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT SP.Nume, SP.DataIncheiereContract, SP.Suma FROM Sponsori SP\n" +
                    "INNER JOIN Sedii S ON SP.SediuID = S.SediuID\n" +
                    "INNER JOIN Angajati A ON S.ManagerID = A.AngajatID\n" +
                    "WHERE A.Nume='Valentin' AND A.Prenume = 'Mihai'\n" +
                    "GROUP BY SP.Nume, SP.DataIncheiereContract, SP.Suma";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq5ActionPerformed

    private void butonq6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq6ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT DISTINCT C.Nume, C.Prenume FROM Clienti C\n" +
                    "INNER JOIN ClientiBiciclete CB ON C.ClientID = CB.ClientID\n" +
                    "INNER JOIN Biciclete B ON CB.BicicletaID = B.BicicletaID\n" +
                    "WHERE B.PretInchirierePeOra BETWEEN ? AND ?";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,jTextField2.getText());
            ps.setString(2,jTextField3.getText());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq6ActionPerformed

    private void butonq8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq8ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT B.Producator, B.Serie, B.Culoare, B.MaterialCadru, B.NumarViteze, B.PretInchirierePeOra\n" +
                    "FROM Biciclete B\n" +
                    "WHERE B.BicicletaID NOT IN (SELECT DISTINCT Bi.BicicletaID\n" +
                    "                           FROM Biciclete Bi, ClientiBiciclete CB\n" +
                    "				WHERE Bi.BicicletaID = CB.BicicletaID AND CB.Data > ?)";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,inputData.getText());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq8ActionPerformed

    private void butonq9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq9ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT month(Data) as Luna, COUNT(BicicletaID) AS NrInchirieri\n" +
                    "FROM ClientiBiciclete\n" +
                    "GROUP BY month(Data)\n" +
                    "HAVING count(BicicletaID)=\n" +
                    "				(SELECT max(s.nrInch)\n" +
                    "				FROM (SELECT (COUNT(BicicletaID)) AS nrInch\n" +
                    "				FROM ClientiBiciclete\n" +
                    "				GROUP BY month(Data)) AS s)";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq9ActionPerformed

    private void butonq10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonq10ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT M.Nume, M.Prenume\n" +
                    "FROM Angajati M\n" +
                    "WHERE M.angajatid in (SELECT a.AngajatID FROM Angajati a \n" +
                    "                       INNER JOIN Sedii se ON a.AngajatID = se.ManagerID \n" +
                    "                       INNER JOIN Sponsori sp ON se.SediuID = sp.SediuID\n" +
                    "                       GROUP BY a.AngajatID\n" +
                    "                       HAVING COUNT(sp.SponsorID) >=?)";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,nrSponsori.getText());
            rs=ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));

            // Closes the Connection

            JOptionPane.showMessageDialog(null, new JScrollPane(table));

        } catch (SQLException ex) {
            Logger.getLogger(Interogari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonq10ActionPerformed

    private void btn_home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home2ActionPerformed
        // TODO add your handling code here:
        HomeScreen hs = new HomeScreen();
        hs.setVisible(true);
        hs.pack();
        hs.setSize(633, 700);
        hs.setLocationRelativeTo(null);
        hs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_home2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interogari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home2;
    private javax.swing.JButton butonq1;
    private javax.swing.JButton butonq10;
    private javax.swing.JButton butonq2;
    private javax.swing.JButton butonq3;
    private javax.swing.JButton butonq4;
    private javax.swing.JButton butonq5;
    private javax.swing.JButton butonq6;
    private javax.swing.JButton butonq7;
    private javax.swing.JButton butonq8;
    private javax.swing.JButton butonq9;
    private javax.swing.JTextField inputData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> modalitatePlata;
    private javax.swing.JTextField nrSponsori;
    private javax.swing.JComboBox<String> sediuNume;
    private javax.swing.JComboBox<String> sediuNume1;
    // End of variables declaration//GEN-END:variables

    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

    }
    }
